spring.application.name=exam-system

# MySQL database configuration

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/exam_v1}
spring.datasource.username=${DB_USERNAME:your_db_user}
spring.datasource.password=${DB_PASSWORD:your_db_password}

spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# JWT Configuration
secret=${JWT_SECRET:your_jwt_secret_key_at_least_256_bits}
expiration=900000
jwt.refresh-token.expiration-minutes=43200


# QR Code Configuration
exam.qr.expiration-minutes=2


# Email Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:your_email@example.com}
spring.mail.password=${MAIL_PASSWORD:your_email_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true



# other 
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.org.hibernate.SQL=error
spring.thymeleaf.check-template-location=false


# \u062A\u063A\u064A\u064A\u0631 \u0645\u0633\u0627\u0631 Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# \u062A\u0639\u0637\u064A\u0644 \u0635\u0641\u062D\u0629 Swagger \u0627\u0644\u0631\u0626\u064A\u0633\u064A\u0629
springdoc.swagger-ui.disable-swagger-default-url=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# \u062A\u0643\u0648\u064A\u0646 \u0648\u0627\u062C\u0647\u0629 \u0627\u0644\u0645\u0633\u062A\u062E\u062F\u0645
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha


# Cloudinary Config
Cloudname= ${CLOUDINARY_CLOUD_NAME:your_cloud_name}
APIKey= ${CLOUDINARY_API_KEY:your_api_key}
APISecret= ${CLOUDINARY_API_SECRET:your_api_secret}
CLOUDINARY_URL=${CLOUDINARY_URL:cloudinary://your_api_key:your_api_secret@your_cloud_name}


# ===============================
# RabbitMQ Connection
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=exam
spring.rabbitmq.password=exam
spring.rabbitmq.virtual-host=/


